#!/bin/sh
input_bam=$1
tumor_id=$2
ToSomVar_path=$3
annovar_path=$4
beagle_path=$5
mosaicForecast_path=$6
gatk_path=$7
ref_fa=$8
prefix=$9

#==>Tumor sample mutation detection from Mutect2 tumor-only mode
###detection
${gatk_path} Mutect2 -R ${ref_fa} -I ${input_bam} -tumor ${tumor_id} -O ${prefix}.vcf
###filtration
${gatk_path} FilterMutectCalls --variant ${prefix}.vcf --output ${prefix}.filter.1.vcf --reference ${ref_fa}
perl ${ToSomVar_path}/script/filter_mutect2.pl -f  ${prefix}.filter.1.vcf -o ${prefix}.filter.2.vcf  ##filtered by reads depth
 
###Extract exonic mutation
less ${prefix}.filter.2.vcf|grep -v '^#'|awk '{print $1"\t"$2"\t"$2"\t"$4"\t"$5}' >${prefix}.filter.2.snp
perl ${annovar_path} ${prefix}.filter.2.snp ${ToSomVar_path}/database/ -buildver hg19 -out ${prefix}.ensGene -protocol ensGene -operation g -nastring . -remove -thread 5
less ${prefix}.ensGene.hg19_multianno.txt|awk '{if($6=="exonic" || $6=="exonic;splicing" )print $1"\t"$2"\t"$2"\t"$4"\t"$5}' > ${prefix}.exonic.snps.bed
 

#==>Feature collection
###Features from mutect2
echo "==>Features collection from mutect2"
perl ${ToSomVar_path}/script/extract_mutectFeatures.pl -f ${prefix}.filter.2.vcf  -s  ${prefix}.exonic.snps.bed -o ${prefix}.mute.features 

###Features from annovar
echo -e "\n==>Features collection from annovar"
perl ${annovar_path} ${prefix}.exonic.snps.bed ${ToSomVar_path}/database/ -buildver hg19 -out ${prefix}.anno -protocol avsnp147,cadd,dbnsfp33a,eigen,icgc21,nci60,snp138NonFlagged -operation f,f,f,f,f,f,f -nastring . -remove -thread 10
perl ${ToSomVar_path}/script/extract_annotatedFeatures.pl -f ${prefix}.exonic.snps.bed -d ${ToSomVar_path}/database -o ${prefix}.hous.features

###Features from imputation
echo -e "\n==>Features collection from imputation"
sh ${ToSomVar_path}/script/impute.sh ${prefix}.filter.1.vcf ${prefix} ${ToSomVar_path} ${beagle_path} ${prefix}.exonic.snps.bed

###Features from MosaicForecast
echo -e "\n==>Features collection from mosaicforecast"
bam_name=`basename ${input_bam}|sed 's/.bam//'`
less ${prefix}.filter.2.vcf|grep -v '^#'|awk '{print $1"\t"$2-1"\t"$2"\t"$4"\t"$5"\t'${bam_name}'"}' > ${prefix}.mosa.input 
bam_dir=`dirname ${input_bam}`
if [ -f "${ToSomVar_path}/database/k24.umap.wg.bw.gz" ]; then
	gunzip ${ToSomVar_path}/database/k24.umap.wg.bw.gz
fi
python ${mosaicForecast_path} ${prefix}.mosa.input ${prefix}.mosa.features ${bam_dir} ${ref_fa} ${ToSomVar_path}/database/k24.umap.wg.bw 90 12 bam
 
###Feature selection
echo "id" > ${prefix}.id
less ${prefix}.mute.features|sed '1d'|cut -f 1-4|sed 's/\t/~/g'|sed 's/^/'${bam_name}'~/' >> ${prefix}.id
awk -F '\t' 'NR==FNR{a[$1]=$2OFS$3OFS$5OFS$6OFS$7OFS$8OFS$9OFS$10OFS$11OFS$12OFS$13OFS$14OFS$15OFS$16OFS$17OFS$18OFS$19OFS$21OFS$22OFS$23OFS$24OFS$25OFS$26OFS$27OFS$28OFS$29OFS$30OFS$31OFS$32OFS$33OFS$34;next}{if($1 in a)print a[$1];else print "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"}' OFS="\t" ${prefix}.mosa.features ${prefix}.id >${prefix}.mosa.features.1
paste ${prefix}.mute.features ${prefix}.impu.features ${prefix}.anno.hg19_multianno.txt ${prefix}.hous.features ${prefix}.mosa.features.1  > ${prefix}.all.features
perl ${ToSomVar_path}/script/extract_allFeatures.pl -f ${prefix}.all.features -o ${prefix}.input.features
 
###Feature normlize
Rscript ${ToSomVar_path}/script/normlize.R ${prefix}.input.features ${prefix}.input.norm.features 
 
###Mutation type prediction
if [ -f "${ToSomVar_path}/database/RF.pkl.gz" ]; then
	gunzip ${ToSomVar_path}/database/RF.pkl.gz
fi
python3 ${ToSomVar_path}/script/predict.py ${prefix}.input.norm.features ${ToSomVar_path}/database/ ${prefix}
paste  ${prefix}.exonic.snps.bed ${prefix}.result|sed 's/-1$/germline/'|sed 's/0$/uncertain/'|sed 's/1$/somatic/' > ${prefix}.result.1; mv  ${prefix}.result.1  ${prefix}.result;
ls ${prefix}.* Mutect2FilteringStats.tsv *-*-*-*|grep -vE 'result|log'|xargs -i echo "rm -f {}"|sh
